module.exports = {
  body:{
    "Inputs": {
      "input1": {
        "ColumnNames": [
          "Apache",
          "OpenSSL",
          "PHP",
          "UNIX",
          "Google Tag Manager",
          "Nginx",
          "Usabilla",
          "jQuery",
          "Optimizely",
          "Tealium",
          "Amazon Cloudfront",
          "Modernizr",
          "Prototype",
          "AngularJS",
          "Incapsula",
          "Moment.js",
          "Acquia Cloud",
          "Google Analytics",
          "New Relic",
          "Varnish",
          "Ruxit",
          "TrackJs",
          "Linkedin",
          "Bootstrap",
          "Visual Website Optimizer",
          "Raphael",
          "Hotjar",
          "Ubuntu",
          "AddToAny",
          "Crazy Egg",
          "Facebook",
          "OWL Carousel",
          "Plesk",
          "Tawk.to",
          "Google Maps",
          "Twitter",
          "Debian",
          "Backbone.js",
          "Lo-dash",
          "Underscore.js",
          "jQuery UI",
          "Chart.js",
          "CloudFlare",
          "AddThis",
          "Google Font API",
          "Highcharts",
          "MailChimp",
          "DoubleClick for Publishers (DFP)",
          "HubSpot",
          "Lightbox",
          "Hammer.js",
          "TweenMax",
          "Font Awesome",
          "Typekit",
          "Red Hat",
          "Fingerprintjs",
          "Slick",
          "ZURB Foundation",
          "Mautic",
          "SumoMe",
          "YouTube",
          "Flickity",
          "Heap",
          "Drupal Commerce",
          "Yii",
          "Lazy.js",
          "RequireJS",
          "jQuery Migrate",
          "AppNexus",
          "Livefyre",
          "Intercom",
          "Piwik",
          "FancyBox",
          "Mixpanel",
          "Dojo",
          "mod_ssl",
          "Mollom",
          "Amazon S3",
          "Less",
          "React",
          "IIS",
          "Windows Server",
          "Dynamicweb",
          "Microsoft ASP.NET",
          "Highlight.js",
          "Wink",
          "Clipboard.js",
          "Zendesk Chat",
          "Laravel",
          "Leaflet",
          "Select2",
          "LiteSpeed",
          "CentOS",
          "EPages",
          "animate.css",
          "particles.js",
          "Google Plus",
          "KineticJS",
          "Yoast SEO",
          "OpenResty",
          "Lua",
          "Google AdSense",
          "Gravity Forms",
          "WP Rocket",
          "WooCommerce",
          "Revslider",
          "Snap.svg",
          "UIKit",
          "prettyPhoto",
          "W3 Total Cache",
          "Ionicons",
          "Gravatar",
          "Twitter Emoji (Twemoji)",
          "MediaElement.js",
          "Google Web Server",
          "TinyMCE",
          "DataTables",
          "jQuery Mobile",
          "Socket.io",
          "Node.js",
          "SWFObject",
          "Criteo",
          "Handlebars",
          "Twitter typeahead.js",
          "Clicky",
          "Materialize CSS",
          "YUI",
          "Google PageSpeed",
          "WordPress Super Cache",
          "SyntaxHighlighter",
          "Nette Framework",
          "Python",
          "mod_python",
          "ShareThis",
          "mod_wsgi",
          "cms"
        ],
        "Values": [
          [
            "0",
            "value",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "value",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "value",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "value",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "value",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "0",
            "value"
          ]
        ]
      }
    },
    "GlobalParameters": {}
  }
}